# Generated by Django 5.0.6 on 2026-04-02 07:34

import apps.jars.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blockchain", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contractevent",
            name="chain_jar_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                help_text="on-chain jar ID from event args (if applicable).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="contractevent",
            name="emitter_wallet",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="The wallet address that triggered this event (indexed arg).",
                max_length=42,
            ),
        ),
        migrations.AlterField(
            model_name="contractevent",
            name="event_data",
            field=models.JSONField(
                default=dict, help_text="Decoded event arguments from ABI."
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="chain_id",
            field=models.PositiveIntegerField(
                default=80002,
                help_text="Chain ID (Amoy=80002, Polygon=137, Hardhat=31337).",
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="donation_id_ref",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="ID of the related Donation record, if applicable.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="from_wallet",
            field=models.CharField(
                db_index=True,
                help_text="Address that initiated the transaction (msg.sender).",
                max_length=42,
                validators=[apps.jars.validators.validate_wallet_address],
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="jar_id_ref",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="ID of the related Jar record, if applicable.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="raw_receipt",
            field=models.JSONField(
                blank=True,
                help_text="Full JSON receipt from web3.py (for debugging/auditing).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="to_wallet",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Destination address (contract address for contract calls).",
                max_length=42,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="tx_hash",
            field=models.CharField(
                db_index=True,
                help_text="Ethereum transaction hash.",
                max_length=66,
                unique=True,
                validators=[apps.jars.validators.validate_tx_hash],
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="value_matic",
            field=models.DecimalField(
                decimal_places=6,
                default=0,
                help_text="Transaction value in MATIC (human-readable).",
                max_digits=20,
            ),
        ),
        migrations.AlterField(
            model_name="transactionlog",
            name="value_wei",
            field=models.CharField(
                default="0",
                help_text="Transaction value in wei (string for precision).",
                max_length=78,
            ),
        ),
    ]
