# Generated by Django 5.0.6 on 2026-04-02 07:34

import apps.jars.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jars", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="jar",
            name="amount_raised_matic",
            field=models.DecimalField(
                decimal_places=6,
                default=Decimal("0.000000"),
                help_text="Total MATIC raised so far (synced from chain).",
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="chain_jar_id",
            field=models.PositiveBigIntegerField(
                blank=True,
                db_index=True,
                help_text="The uint256 jar ID from the smart contract (set after on-chain confirmation).",
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="cover_emoji",
            field=models.CharField(
                default="🫙",
                help_text="Single emoji used as the jar's cover icon.",
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="cover_image_url",
            field=models.URLField(
                blank=True, default="", help_text="Optional cover image URL."
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="creation_tx_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                default="",
                help_text="Tx hash of the createJar() transaction.",
                max_length=66,
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="creator",
            field=models.ForeignKey(
                help_text="The authenticated user who created this jar.",
                on_delete=django.db.models.deletion.PROTECT,
                related_name="jars",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="creator_wallet",
            field=models.CharField(
                db_index=True,
                help_text="Checksum Ethereum address of the creator (denormalized from creator.wallet_address).",
                max_length=42,
                validators=[apps.jars.validators.validate_wallet_address],
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="deadline",
            field=models.DateTimeField(
                db_index=True,
                help_text="Deadline after which the creator can withdraw funds.",
                validators=[apps.jars.validators.validate_future_deadline],
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="description",
            field=models.TextField(
                help_text="Full description of the fundraiser (max 1000 chars).",
                max_length=1000,
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="donor_count",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of unique donors (cached from chain/donations table).",
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="is_verified_on_chain",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True once the creation tx has been confirmed on-chain.",
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="target_amount_matic",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Fundraising target in MATIC.",
                max_digits=20,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="title",
            field=models.CharField(
                db_index=True,
                help_text="Short name of the fundraiser (max 120 chars, matches contract limit).",
                max_length=120,
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="withdrawal_tx_hash",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Tx hash of the withdraw() call.",
                max_length=66,
            ),
        ),
        migrations.AlterField(
            model_name="jar",
            name="withdrawn_at",
            field=models.DateTimeField(
                blank=True, help_text="When the creator withdrew the funds.", null=True
            ),
        ),
    ]
