# Generated by Django 5.0.6 on 2026-04-02 07:34

import apps.jars.validators
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("donations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="donation",
            name="amount_matic",
            field=models.DecimalField(
                decimal_places=6,
                help_text="Donation amount in MATIC.",
                max_digits=20,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0.001")),
                    apps.jars.validators.validate_min_donation,
                ],
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="amount_wei",
            field=models.CharField(
                default="0",
                help_text="Exact donation amount in wei (string to avoid float precision loss).",
                max_length=78,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="block_number",
            field=models.PositiveBigIntegerField(
                blank=True,
                help_text="Block number in which the tx was mined.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="block_timestamp",
            field=models.DateTimeField(
                blank=True,
                help_text="Block timestamp from the chain (may differ slightly from created_at).",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="confirmations",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Number of block confirmations at last verification check.",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                blank=True,
                help_text="Linked user account (null if donor wallet not registered).",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor_wallet",
            field=models.CharField(
                db_index=True,
                help_text="Checksum Ethereum address of the donor.",
                max_length=42,
                validators=[apps.jars.validators.validate_wallet_address],
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="gas_price_gwei",
            field=models.DecimalField(
                blank=True,
                decimal_places=9,
                help_text="Gas price in gwei.",
                max_digits=20,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="gas_used",
            field=models.PositiveBigIntegerField(
                blank=True, help_text="Gas consumed by the donate() call.", null=True
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="is_anonymous",
            field=models.BooleanField(
                default=False,
                help_text="If True, donor wallet is hidden from public API responses.",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="is_verified",
            field=models.BooleanField(
                db_index=True,
                default=False,
                help_text="True once the required number of block confirmations is reached.",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="last_verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Last time the Celery worker checked this transaction.",
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="message",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Optional donor message (Twitter/X-style, 280 chars).",
                max_length=280,
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="tx_hash",
            field=models.CharField(
                db_index=True,
                help_text="Ethereum transaction hash of the donate() call.",
                max_length=66,
                unique=True,
                validators=[apps.jars.validators.validate_tx_hash],
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="verification_attempts",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="How many times the verification Celery task has polled this tx.",
            ),
        ),
        migrations.AlterField(
            model_name="donation",
            name="verified_at",
            field=models.DateTimeField(
                blank=True,
                help_text="When the transaction was confirmed and verified.",
                null=True,
            ),
        ),
    ]
